app:
  port: ':33333'
  auth: 'y1t-gov'
db:
  type: 'mysql'
  host: 'localhost'
  port: '3306'
  user: 'user'
  passwd: '123456'
  dbName: 'y1t_gov'
logger:
  fileName: 'permissions.log'
  filePath: 'log'
jwt:
  signKey: 'y1t'
  timeout: '10'
  iss: 'y1t'
  bufferTime: '5'